[platformio]
default_envs = m5stack-cores3

[env]
platform = espressif32
framework = arduino
lib_deps = 
    AccelStepper
    ArduinoEigen
    Module_Stepmotor
    https://github.com/lvgl/lvgl.git#release/v8.3
    https://github.com/lovyan03/LovyanGFX
build_flags = 
    -Wall -Werror
   	-D DEBUG=1
   	; -D LV_CONF_INCLUDE_SIMPLE=1
   	-I .
	-I include

build_type = debug
monitor_filters =
    esp32_exception_decoder

[env:m5stack-core]
board = m5stack-core-esp32
build_flags = 
    ${env.build_flags}
lib_deps = 
    ${env.lib_deps}
    ; m5stack/M5Stack
monitor_speed = 115200

[env:m5stack-core2]
board = m5stack-core2
build_flags = 
    ${env.build_flags}
lib_deps = 
    ${env.lib_deps}
    ; m5stack/M5Core2
monitor_speed = 115200

[env:m5stack-cores3]
board = m5stack-cores3
build_unflags =
    -D ARDUINO_USB_MODE
build_flags = 
    ${env.build_flags}
    ;-DBOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=0           ; Configures the ESP32 USB as OTG, sw controlled, routes "Serial" to USBCDC, no programming
    -D ARDUINO_USB_CDC_ON_BOOT=1    ; Configure USBCDC on OTG, USB_MODE must be 0 (sw)
    ; -D ARDUINO_USB_MODE=1           ; Configures the ESP32 USB as native (hw): CDC+JTAG (default)
    ; -D ARDUINO_USB_MODE=2           ; Configures the ESP32 USB as native (hw): Serial JTAG Mode
    ; -D ARDUINO_USB_MODE=3           ; Configures the ESP32 USB as native (hw): DFU Mode
lib_deps = 
    ${env.lib_deps}
    ; m5stack/M5CoreS3
monitor_speed = 460800
; upload_protocol = esptool ;default
; upload_protocol = esp-prog
debug_tool = esp-builtin
; debug_load_mode = manual
; debug_init_break = tbreak setup
; debug_speed = 12000
; debug_load_module = modified
