
#include "tools-keys.h"

typedef enum : uint32_t
{
	KEY_NONE = 0x00,
    // KEY_LONG_RELEASED = KEYTOOL_LONG_RELEASED,

    // key defs
	KEY_RED = 0x01,
	KEY_GREEN = 0x02,
	KEY_BLUE = 0x04,
	KEY_YELLOW = 0x08,

	// combinations
	// KEY_REDGREEN = KEY_RED | KEY_GREEN,
    // etc..

    // single key modes
    KEY_RED_SHORT = KEY_RED | KEYTOOL_SHORT,
    KEY_GREEN_SHORT = KEY_GREEN | KEYTOOL_SHORT,
    KEY_BLUE_SHORT = KEY_BLUE | KEYTOOL_SHORT,
    KEY_YELLOW_SHORT = KEY_YELLOW | KEYTOOL_SHORT,

    // KEY_RED_LONG = KEY_RED | KEYTOOL_LONG,
    // KEY_GREEN_LONG = KEY_GREEN | KEYTOOL_LONG,
    // KEY_BLUE_LONG = KEY_BLUE | KEYTOOL_LONG,
    // KEY_YELLOW_LONG = KEY_YELLOW | KEYTOOL_LONG,

    // KEY_RED_LONG_REPEAT = KEY_RED | KEYTOOL_LONG_REPEAT,
    // KEY_GREEN_LONG_REPEAT = KEY_GREEN | KEYTOOL_LONG_REPEAT,
    // KEY_BLUE_LONG_REPEAT = KEY_BLUE | KEYTOOL_LONG_REPEAT,
    // KEY_YELLOW_LONG_REPEAT = KEY_YELLOW | KEYTOOL_LONG_REPEAT,

} keypress_t;
